on: "push"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Pages
          uses: actions/configure-pages@v5
        - name: Build
          uses: ./
        - name: Upload built file
          uses: actions/upload-artifact@v4
          with:
            name: workspace_artifacts
            path: ${{ github.workspace }}/web-built