name: Build
on: "push"
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./
      - name: Upload web artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: web-artifact
          path: ${{ github.workspace }}/web-artifact
      - name: Upload apk artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifact
          path: ${{ github.workspace }}/app-release.apk
    deploy:
      runs-on: ubuntu-latest
      needs: build
      permissions:
        pages: write    
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: web-artifact

